# Конфигурация нагрузочного теста KM_track
# Запуск: locust -f locustfile.py --config locust.conf

host = http://localhost:8000
users = 10000
spawn-rate = 200
run-time = 5m
headless = false
html = locust_report.html
