name: "Жара"
display_name: "Жара"
year: 2026
code: "zhara"

distances:
  - distance: "21.1 км"
    distance_km: 21.1
    db_event_id: null
    tracked: true
    has_start_list: true
    checkpoint_distances: null
    gpx_file: null
    event_date: null
    copernico:
      race_id: null
      login: "podbor250718@gmail.com"
      preset: "km_analytics"
      event: "21.1 км"

  - distance: "5 км"
    distance_km: 5.0
    db_event_id: null
    tracked: true
    has_start_list: true
    checkpoint_distances: null
    gpx_file: null
    event_date: null
    copernico:
      race_id: null           # отдельный race_id для дистанции 5 км
      login: "podbor250718@gmail.com"
      preset: "km_analytics"
      event: "5 км"

  - distance: "2 км"
    distance_km: 2.0
    db_event_id: null
    tracked: false
    has_start_list: true
