name: "Жара"
display_name: "Жара"
year: 2026
code: "zhara"
is_active: false              # ← АКТИВНЫЙ забег: true у одного, false у остальных
start_lat: 56.0126030               # ← заполнить перед стартом
start_lon: 92.8936640               # ← заполнить перед стартом
gun_time: null                # ← заполнить перед стартом (разные для дистанций?)
description: "Жара | Дистанции: 5 км, 21.1 км"

distances:
  - distance: "21.1 км"
    distance_km: 21.1
    db_event_id: 116         # ← заполнить перед стартом
    tracked: true
    has_start_list: true
    checkpoint_distances: []
    checkpoints: []           # ← заполнить перед стартом
    gpx_file: "static/map/2026/zhara_21.gpx"            # ← заполнить перед стартом
    event_date: "2026-08-23"         # ← заполнить перед стартом
    route:
      laps: 1
      total_km: 21.1
    copernico:
      race_id: null           # ← заполнить перед стартом
      login: "podbor250718@gmail.com"
      preset: "km_analytics"
      event: "21.1 км"

  - distance: "5 км"
    distance_km: 5.0
    db_event_id: 115         # ← заполнить перед стартом
    tracked: true
    has_start_list: true
    checkpoint_distances: []
    checkpoints: []           # ← заполнить перед стартом
    gpx_file: "static/map/2026/zhara_5.gpx"            # ← заполнить перед стартом
    event_date: "2026-08-22"          # ← заполнить перед стартом
    route:
      laps: 1
      total_km: 5.0
    copernico:
      race_id: null           # ← отдельный race_id для дистанции 5 км
      login: "podbor250718@gmail.com"
      preset: "km_analytics"
      event: "5 км"

  - distance: "2 км"
    distance_km: 2.0
    db_event_id: null
    tracked: false
    has_start_list: true
    checkpoint_distances: []
    route:
      laps: 1
      total_km: 2.0
