description: "Первомайский полумарафон 2026, 21.1км. 7 КТ. Chip-времена не предоставляются."

fields:
  bib: dorsal
  surname: surname
  name: name
  birthdate: birthdate
  gender: gender
  status: status
  category: category

time_fields:
  gun_start:   "times.official_:::start:::"
  gun_finish:  "times.official_:::finish:::"
  chip_start:  null
  chip_finish: null

checkpoint_fields:
  kt1: "times.official_3km"
  kt2: "times.official_5.3km"
  kt3: "times.official_8.3km"
  kt4: "times.official_10.6km"
  kt5: "times.official_13.6km"
  kt6: "times.official_15.9"       # без суффикса km — аномалия в Copernico
  kt7: "times.official_18.9km"
